name: Init
description: Init
runs:
  using: composite
  steps:
    - uses: valitydev/action-frontend/setup@v0.1
    - run: npm ci --force # TODO: Remove "--force" after updating Angular in external libraries (@vality)
      shell: bash
