name: Init
description: Init
runs:
    using: composite
    steps:
        - name: Init NodeJS
          uses: actions/setup-node@v2
          with:
              node-version: '16.13.2'
              cache: 'npm'

        - name: Install Packages
          run: npm ci
          shell: bash
