name: Init
description: Init
runs:
    using: composite
    steps:
        - uses: valitydev/action-frontend/setup@v0.1
        - run: npm ci
          shell: bash
        - name: Generate Swagger & OpenAPI code
          run: npm run codegen
          shell: bash
