name: Main
on:
  push:
    branches: ['master', 'main', 'epic/**']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init
      - name: Build
        run: npm run build
      - name: Deploy image
        uses: valitydev/action-deploy-docker@v2
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: set config
        run: |
          printf "$APP_ENV_FILE" > dist/appConfig.json
          printf "$AUTH_ENV_FILE" > dist/authConfig.json
          echo $FAVICO | base64 -d -o dist/favicon.ico
          printf "$LOGO" > dist/assets/icons/logo.svg
        env:
          APP_ENV_FILE: ${{secrets.APP_CONFIG_CF}}
          AUTH_ENV_FILE: ${{secrets.AUTH_CONFIG_CF}}
          FAVICO: ${{secrets.FAVICON_BASE}}
          LOGO: ${{secrets.LOGO_SVG}}
      - name: Publish to CF Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'dashboard'
          directory: 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
