name: Main
on:
  push:
    branches: ['master', 'main', 'epic/**']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Build
        run: npm run build
      - name: Deploy image
        uses: valitydev/action-deploy-docker@v2
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set config
        run: |
          printf "$APP_ENV_FILE" > dist/browser/assets/appConfig.json
          printf "$AUTH_ENV_FILE" > dist/browser/assets/authConfig.json
        env:
          APP_ENV_FILE: ${{secrets.APP_CONFIG_CF}}
          AUTH_ENV_FILE: ${{secrets.AUTH_CONFIG_CF}}
      - name: Publish to CF Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'dashboard'
          directory: 'dist/browser'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Set pcigate config
        run: |
          printf "$APP2_ENV_FILE" > dist/browser/assets/appConfig.json
        env:
          APP2_ENV_FILE: ${{secrets.APP2_ENV_FILE}}
      - name: Publish pcigate to CF Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'dashboard-pgate'
          directory: 'dist/browser'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Set globalgatein config
        run: |
          printf "$APP3_ENV_FILE" > dist/browser/assets/appConfig.json
        env:
          APP3_ENV_FILE: ${{secrets.APP3_ENV_FILE}}
      - name: Publish globalgatein to CF Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'dashboard-globalgatein'
          directory: 'dist/browser'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Set flow3dtunnel config
        run: |
          printf "$APP4_ENV_FILE" > dist/browser/assets/appConfig.json
        env:
          APP4_ENV_FILE: ${{secrets.APP4_ENV_FILE}}
      - name: Publish flow3dtunnel to CF Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'dashboard-flow3dtunnel'
          directory: 'dist/browser'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-mattermost-notify@v0.1.4
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: 'frontend'
          username: 'Frontend'
