name: 'PR: Build & Check'
on:
    pull_request:
        branches: ['*']
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: recursive

            - name: Init
              uses: ./.github/actions/init

            - name: Check & Build
              run: npm run ci:build
