name: PR
on:
  pull_request:
    branches: ['*']
jobs:
  init:
    name: Initialization
    runs-on: ubuntu-latest
    steps:
#      - uses: actions/checkout@v3
#      - uses: ./.github/actions/init
#      - name: Cache all
#        uses: actions/cache@v3
#        id: cache
#        with:
#          path: ./*
#          key: ${{ github.sha }}
      - name: Mattermost Notification
#        if: steps.cache.outcome == 'success'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "test"
          SLACK_USERNAME: "Frontend"
          SLACK_ICON_EMOJI: ":tractor:"
          SLACK_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ${{ github.head_ref }}.${{ github.sha }}
          MSG_MINIMAL: true
          SLACK_TITLE: ${{ github.repository }}
          SLACK_MESSAGE: |
            **[${{ github.event.pull_request.title }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }})**
            ${{ github.event.pull_request.body }}

#  format:
#    name: Format check
#    runs-on: ubuntu-latest
#    needs: [init]
#    steps:
#      - name: Cache all
#        uses: actions/cache@v3
#        id: cache
#        with:
#          path: ./*
#          key: ${{ github.sha }}
#      - name: Check
#        run: npm run format
#  lint:
#    name: Lint check
#    runs-on: ubuntu-latest
#    needs: [init]
#    steps:
#      - name: Cache all
#        uses: actions/cache@v3
#        id: cache
#        with:
#          path: ./*
#          key: ${{ github.sha }}
#      - name: Check
#        run: npm run lint
#  i18n:
#    name: Translation keys check
#    runs-on: ubuntu-latest
#    needs: [init]
#    steps:
#      - name: Cache all
#        uses: actions/cache@v3
#        id: cache
#        with:
#          path: ./*
#          key: ${{ github.sha }}
#      - name: Check
#        run: npm run i18n:check
#  spell:
#    name: Spell check
#    runs-on: ubuntu-latest
#    needs: [init]
#    steps:
#      - name: Cache all
#        uses: actions/cache@v3
#        id: cache
#        with:
#          path: ./*
#          key: ${{ github.sha }}
#      - name: Check
#        run: npm run spell
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    needs: [init]
#    steps:
#      - name: Cache all
#        uses: actions/cache@v3
#        id: cache
#        with:
#          path: ./*
#          key: ${{ github.sha }}
#      - name: Build
#        run: npm run build