name: PR
on:
  pull_request:
    branches: ['*']
jobs:
  check2:
    name: Check 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - uses: npm run format
      - uses: npm run lint
      - uses: npm run spell
      - uses: npm run i18n:check
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Check
        run: npm run check
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Build
        run: npm run build
