name: PR
on:
    pull_request:
        branches: ['*']
jobs:
    init:
        name: Init
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - uses: ./.github/actions/init
            - name: Cache all
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
    prettier:
        name: Prettier
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache all
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Check
              run: npm run prettier
    eslint:
        name: ESLint
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache all
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Check
              run: npm run lint-cmd
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache all
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Build
              run: npm run build
