name: PR
on:
    pull_request:
        branches: ['*']
jobs:
    init:
        name: Initialization
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/init
            - name: Cache all
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
    prettier:
        name: Prettier check
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache all
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Check
              run: npm run prettier
    eslint:
        name: ESLint check
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache all
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Check
              run: npm run lint-cmd
    i18n:
        name: Translation keys check
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache all
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Check
              run: npm run i18n:find
    build:
        name: Build
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - name: Cache all
              uses: actions/cache@v3
              id: cache
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Build
              run: npm run build
