name: PR
on:
  pull_request:
    branches: ['*']
jobs:
  init:
    name: Initialization
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Cache all
        uses: actions/cache@v3
        id: cache
        with:
          path: ./*
          key: ${{ github.sha }}
  format:
    name: Format check
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Cache all
        uses: actions/cache@v3
        id: cache
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Check
        run: npm run format
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Cache all
        uses: actions/cache@v3
        id: cache
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Check
        run: npm run lint
  i18n:
    name: Translation keys check
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Cache all
        uses: actions/cache@v3
        id: cache
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Check
        run: npm run i18n:check
  spell:
    name: Spell check
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Cache all
        uses: actions/cache@v3
        id: cache
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Check
        run: npm run spell
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Cache all
        uses: actions/cache@v3
        id: cache
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Build
        run: npm run build
