name: PR
on:
  pull_request:
    branches: ['*']
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: valitydev/action-frontend/setup-install@v3
        with:
          force: true
      - name: Check
        run: npm run check
      - name: Build
        run: npm run build
